# Generated by Django 5.1.5 on 2025-02-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-deadline"]},
        ),
    ]
