# Generated by Django 5.1.5 on 2025-02-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("P1", "Critical"),
                    ("P2", "High"),
                    ("P3", "Medium"),
                    ("P4", "Low"),
                    ("P5", "No priority"),
                ],
                max_length=20,
            ),
        ),
    ]
