# Generated by Django 5.1.5 on 2025-02-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_priority"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["name"]},
        ),
    ]
